---
title: "Big Data Bowl 2022"
author: "Mar and Eli"
date: "10/26/2021"
output: html_document
---
load packages
```{r}
library(tidyverse)
library(gganimate)
library(gifski)
library(repr)
```

```{r}

#setting plot width and height
options(repr.plot.width=15, repr.plot.height = 10)


```
Read in data
```{r}
games <- read_csv('data/games.csv')
pff <- read_csv('data/PFFScoutingData.csv')
players <- read_csv('data/players.csv')
plays <- read_csv('data/plays.csv')
tracking2018 <- read_csv('data/tracking2018.csv')
```

Read in 2019 and 2020 tracking data if you want
```{r}
tracking2019 <- read_csv('data/tracking2019.csv')
tracking2020 <- read_csv('data/tracking2020.csv')
```

#Standardizing tracking data so its always in direction of kicking team.
```{r}
tracking2018 <- tracking2018 %>%
                mutate(x = ifelse(playDirection == "left", 120-x, x),
                       y = ifelse(playDirection == "left", 160/3 - y, y))
```

Trying to plot a field goal using Tom Bliss' tutorial

Filter data to an Eagles game winner :)
```{r}
Eagles_Plays <- plays %>% 
  filter(possessionTeam == 'PHI' & specialTeamsPlayType == 'Field Goal')

jake_elliot_bomb <- tracking2018 %>% 
  filter(gameId == 2018111111 & playId == 1735)
```

```{r}
#upright dimensions
uprightLength = 18.5/3
uprightYardline = 120
uprightAccrossFieldLocation = 160/6
uprightColor = "#E8DE35"
uprightlineWidth = 2
uprightShape = 21
uprightSize = 4
uprightOutlineColor = 'black'

#attributes used for plot. first is away, second is football, third is home.
cols_fill <- c("dodgerblue1", "#663300", "#004C54")
cols_col <- c("#000000", "#663300", "#000000")
size_vals <- c(6, 4, 6)
shape_vals <- c(21, 16, 21)
plot_title <- jake_elliot_bomb$playDescription[1]
nFrames <- max(jake_elliot_bomb$frameId)
```

```{r}
source('https://raw.githubusercontent.com/mlfurman3/gg_field/main/gg_field.R')
```
plotting play and field
```{r}
jakeGIF <- ggplot() +


        #creating field underlay
        gg_field(yardmin = 60, yardmax = 122) +

        #filling forest green for behind back of endzone
        theme(panel.background = element_rect(fill = 'forestgreen',
                                              color = 'forestgreen'),
              panel.grid = element_blank()) +


        #adding field goal uprights
        annotate(geom = 'segment',
                 x = uprightYardline,
                 xend = uprightYardline,
                 y = uprightAccrossFieldLocation + uprightLength/2,
                 yend = uprightAccrossFieldLocation - uprightLength/2,
                 color = uprightColor,
                 lwd = uprightlineWidth) +

        annotate(geom = 'point',
                 x = uprightYardline,
                 y = uprightAccrossFieldLocation + uprightLength/2,
                 size = uprightSize,
                 shape = uprightShape,
                 fill = uprightColor,
                 color = uprightOutlineColor) +

        annotate(geom = 'point',
                 x = uprightYardline,
                 y = uprightAccrossFieldLocation - uprightLength/2,
                 size = uprightSize,
                 shape = uprightShape,
                 fill = uprightColor,
                 color = uprightOutlineColor)+
  
        scale_size_manual(values = size_vals, guide = FALSE) + 
        scale_shape_manual(values = shape_vals, guide = FALSE) +
        scale_fill_manual(values = cols_fill, guide = FALSE) + 
        scale_colour_manual(values = cols_col, guide = FALSE) +


        #adding players
        geom_point(data = jake_elliot_bomb, aes(x = x,
                                          y = y, 
                                          shape = team,
                                          fill = team,
                                          group = nflId,
                                          size = team,
                                          colour = team), 
                 alpha = 0.7) +  

        #adding jersey numbers
        geom_text(data = jake_elliot_bomb,
                  aes(x = x, y = y, label = jerseyNumber),
                  colour = "white", 
                vjust = 0.36, size = 3.5) + 


        #titling plot with play description
        labs(title = 'Jake Elliot 56 yards is good') +

        #setting animation parameters
        transition_time(frameId)  +
        ease_aes('linear') + 
        NULL 

```

```{r}
#saving animation to display in markdown cell below:
suppressWarnings(animate(jakeGIF, width = 720, height = 440,
        fps = 10, nframe = nFrames, renderer = gifski_renderer()))
```


